# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: gmaps_development
  username: root
  password: "123"
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: gmaps_test
  username: root
  password: "123"
  pool: 5
  timeout: 5000

production:
#  adapter: sqlite3
#  database: db/production.sqlite3
#  pool: 5
#  timeout: 5000
  adapter: mysql2
  database: gmaps_development
  username: root
  password: "lcstore2020"
  pool: 5
  timeout: 5000